# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.
version: '3'
services:
  app:
    build: .
    image: blog:1.0.0
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ROCKET_ADDRESS=${ROCKET_ADDRESS}
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "diesel migration run && ./blog"
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    healthcheck:
      test: ["CMD-SHELL","pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10