# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.

version: '3.8'
services :
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=prod

  nginx:
    image: nginx:1.25.3-alpine

    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./.docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

