# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.

version: '3'
services:
  client:
    container_name: client
    build: client
    ports:
      - "4173:80"
    depends_on:
      - server

  nginx:
    container_name: nginx
    image: nginx:1.25.3-alpine
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "5173:80"
    depends_on:
      - client

  server:
    container_name: server
    build: server
    ports:
      - "3000:3000"
