# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.

version: '3'
services:
  client:
    container_name: client
    build: client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - "dbdata:/client/"

  server:
    container_name: server
    build: server
    ports:
      - "8080:3000"
    volumes:
      - "dbdata:/server/"

volumes:
  dbdata:
