# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.

version: '3'
services:
  client:
    container_name: client
    build: client
    ports:
      - ${CLIENT_PORTS}
    depends_on:
      - server

  nginx:
    container_name: nginx
    image: nginx:1.25.3-alpine
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - ${NGINX_PORTS}
    depends_on:
      - client

  server:
    container_name: server
    build: server
    ports:
      - ${SERVER_PORTS}
